### ISSUE TITLE
"Flickering" and missing headlines

### ISSUE THREAD

**Issue by refaelsh** [nvim-orgmode/orgmode#378]
### Describe the bug

Hard to describe in words, please see the attached screenshot, and then I will try to explain in words.
Saw the screenshot? Great.

![WhatsApp Image 2022-07-27 at 8 13 21 PM](https://user-images.githubusercontent.com/2750775/181310607-f84d7d50-b776-47c3-bb55-51a5a7390870.jpeg)

1. There are some headings missing, between lines 76 and 298. They are definitely there, I remember entering them and I can see them when doing `cat file.org`.
2. Line 298, the background of the heading looks "garbled" on the left side.
3. After line 311 there are some strange thingies.
4. And many more strange "flickering" that are hard to describe in words.

### Steps to reproduce

Here the org file to reproduce it: https://pastebin.pl/view/6d3fc321.

### Expected behavior

I should see none of the described problems.

### Minimal init.lua

I tried it with the minimal init.lua, and everything works.
So, the problem is definetly on my side.
Could you please provide ideas on how to debug it?

### OS / Distro

NixOS

### Neovim version/commit

0.7.2

**Comment by jgollenz** [comment]
Unfortunately I know of no better way than to individually disabling your plugins or disabling all of them and gradually bring them back in. I know, it sucks. If someone has a better approach, let me know. Ofc, you can also bisect the list of your plugins to speed up the process

**Comment by refaelsh** [comment]
> Unfortunately I know of no better way than to individually disabling your plugins or disabling all of them and gradually bring them back in. I know, it sucks. If someone has a better approach, let me know. Ofc, you can also bisect the list of your plugins to speed up the process

I will do it asap and report back. Thank you very much for your suggestion.

**Comment by refaelsh** [comment]
Found it. It is this one: https://github.com/lukas-reineke/headlines.nvim.
It is one of the recommended plugins from here: https://github.com/nvim-orgmode/orgmode#plugins.

Please suggest how to proceed :-)

**Comment by jgollenz** [comment]
@lukas-reineke any suggestions? I'm not using headlines.nvim

**Comment by lukas-reineke** [comment]
1. Not sure about the missing lines.. it might have something to do with the folding? But I can't reproduce this, can you share a file for which this happens?
2. This happens because your org headline highlight groups have a background color. https://github.com/akinsho/org-bullets.nvim uses that color for the bullets, but the background color of virtual text overwrites the highlight of the headline from headlines.nvim. To fix this, you have to remove the background color from `OrgHeadlineLevel{1-39}`.
A quick and dirty way to do this without messing with your colorscheme would be something like this

```lua
for i = 1, 40, 1 do
    vim.cmd(string.format("highlight OrgHeadlineLevel%d guibg=NONE", i))
end
```

3. This happens because your font does not support the default character for headlines.nvim. You can either change/patch your font, or use a different character. For example this one

```lua
require("headlines").setup {
   	org = {
        fat_headline_lower_string = "▔",
    },
}
```

4. Not sure about this one either

If you can show me how to reproduce 1 and 4 I can take another look.
And we should probably close this issue here and open a new one in headlines.nvim

**Comment by refaelsh** [comment]
> And we should probably close this issue here and open a new one in headlines.nvim

Done.
