### ISSUE TITLE
Add removal` option/action for Schedule/Deadline

### ISSUE THREAD

**Issue by changyiyao** [nvim-orgmode/orgmode#397]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://orgmode.org/org.html#Inserting-deadline_002fschedule

> 8.3.1 Inserting deadlines or schedules

> When called with a prefix argument, also remove any existing deadline from the entry.

> When called with a prefix argument, also remove the scheduling date from the entry.

**Comment by jgollenz** [comment]
What do you think about `<Leader>ord` and `<Leader>ors` for deadlines and schedules respectively? The `r` stands for remove ofc.

**Comment by changyiyao** [comment]
I prefer `rs`, `rd`. The `r` can be extended to remove tags, properties, which may not be toggled.😀

**Comment by jgollenz** [comment]
Sounds reasonable :+1: I won't be able to give this a shot for a couple of weeks from now, fyi

**Comment by kristijanhusak** [comment]
I solved this by introducing `r` shortcut to the calendar popup. Once you do `<Leader>oid` and calendar appears, pressing `r` closes the calendar and removes the date. Works for both deadline and schedule. We cannot use `rd` and `rs` mappings since they are not prefixed with `<Leader>o`, and generally having a separate mapping complicates it because Emacs doesn't have a dedicated mapping for it, just a prefix.
