### ISSUE TITLE
In week agenda view the tag are not shown fully

### ISSUE THREAD

**Issue by Nithin745** [nvim-orgmode/orgmode#433]
### Describe the bug

The tags on the heading are going beyond screen, had to scroll to the right to see the tags.

### Steps to reproduce

open agenda to view the week agenda.

### Expected behavior

Show the tags within the screen, i.e without need for horizontal scroll

### Minimal init.lua

n/a

### Screenshots and recordings

![Screenshot from 2022-10-30 01-36-55](https://user-images.githubusercontent.com/85417614/198850853-5abb2f70-ae3e-4248-a46b-e0d25f7b8b0c.png)
![Screenshot from 2022-10-30 01-37-04](https://user-images.githubusercontent.com/85417614/198850857-5ce4e68a-c12a-4d9d-9db5-4abcfb87e415.png)

### OS / Distro

fedora 36

### Neovim version/commit

0.9

**Comment by jgollenz** [comment]
@Nithin745 do you have set the `org_tags_column` option in in your config?

**Comment by Nithin745** [comment]
> @Nithin745 do you have set the `org_tags_column` option in in your config?

yes i set it to 50 and also checked with 20. still the look the same
`
require('orgmode').setup{
    org_agenda_files = {'~/Public/orgmode/agenda/*', '~/Public/orgmode/notes/**/*'},
    org_default_notes_file = '~/Public/orgmode/notes/refile.org',
    org_capture_templates = {
         n = {
          description = 'Notes',
          template = '#+TITLE: %?\n#+DATE: %t\n',
          target = '~/Public/orgmode/notes/refile.org'
        }
    },
    org_tags_column = 20
    -- win_split_mode = {'float', .9}
}

`

**Comment by anton-fomin** [comment]
I had the same problem and turning of the sign column helped. I end up with an autocommand for that
```
vim.api.nvim_create_autocmd("FileType", {
    pattern = "orgagenda",
    callback = function()
        vim.cmd[[
        set nornu
        set nonu
        set signcolumn=no
        ]]
    end
})
```

**Comment by Nithin745** [comment]
> vim.api.nvim_create_autocmd("FileType", {
>     pattern = "orgagenda",
>     callback = function()
>         vim.cmd[[
>         set nornu
>         set nonu
>         set signcolumn=no
>         ]]
>     end
> })
Yes this works, but the left side contents too close to the edge of the screen, so turned on only the signcolumn now it looks much better.
signcolumn=no
![Screenshot from 2022-10-30 18-03-39](https://user-images.githubusercontent.com/85417614/198878709-a347d9f0-4f81-445c-9e09-9a06013b4433.png)

signcolumn=yes
![Screenshot from 2022-10-30 18-03-10](https://user-images.githubusercontent.com/85417614/198878711-f7514969-9862-4cc4-8dd9-09e730e4b649.png)

**Comment by jgollenz** [comment]
> set it to 50 and also checked with 20. still the look the same

My bad, this option does not influence how the tags are displayed in the agenda.

@anton-fomin @Nithin745 could you please try whether this also happens when you run neovim with the minimal config? `nvim -u /path/to/orgmode/scripts/minimal_init.lua your-file.org`

**Comment by kristijanhusak** [comment]
> @anton-fomin @Nithin745 could you please try whether this also happens when you run neovim with the minimal config? nvim -u /path/to/orgmode/scripts/minimal_init.lua your-file.org

And also if it fixes itself if you press `r` to refresh the agenda?

**Comment by Nithin745** [comment]
> @anton-fomin @Nithin745 could you please try whether this also happens when you run neovim with the minimal config? `nvim -u /path/to/orgmode/scripts/minimal_init.lua your-file.org`

In the minimal config it is not happening, but i think (like @anton-fomin said) culprit is the sign column, because when i add the sign column to the minimal-config the tags are once again out of screen.

> And also if it fixes itself if you press r to refresh the agenda?
Refreshing the agenda by pressing the `r` is also not working, when signcolumn is present in both my config and minimal-config

mininmal-config with signcolumn and relativenumbers
![Screenshot from 2022-10-30 22-25-41](https://user-images.githubusercontent.com/85417614/198891223-6bc7d17e-ab27-45c6-8143-7b9e1275c1e3.png)


mininmal-config with out signcolumn and relativenumbers

![Screenshot from 2022-10-30 22-26-22](https://user-images.githubusercontent.com/85417614/198891170-64048f47-c5d5-4b1b-906b-47a597ff950f.png)

**Comment by jgollenz** [comment]
I've started looking into this. The issue is that we are only checking if the (rel)numbers column is present. What we should do instead is getting the whole gutter width with `getwininfo().textoff`, but unfortunately we are determining the content of the agenda (including the offset between agenda-items and their tags) before the window in question is even created. @kristijanhusak would there be a drawback to calling `Agenda:open_window` from `Agenda:new` or wherever suitable, as long as it is before we call e.g. `Agenda:agenda`? We could then add another field `win_width` to store `getwininfo().textoff`, that we then pass to the views via the opts. This would also make the call to `utils.winwidth` for every agenda item obsolete.

**Comment by jgollenz** [comment]
> If you think there is some value to not override those

Well, personally I think the num and relnum columns are valuable, because I use them for vertical navigation. My agenda gets quite long sometimes and `17j` beats pressing `j` seventeen times any day.

>  maybe check the getwininfo().textoff in the current org file

@gerazov I don't think this will be consistent. E.g. I have org files with thousands of lines, making the `textoff` value at least four, whereas the aganda has a couple of hundred lines tops (ok, `vy` almost exceeds 1k for me, but still), so the value would be three. The sign column itself also has no predictable width, as multiple plugins might use it. For instance, I do use gitsigns, which usually means that a sign column is present in the buffer of my org file, but it is not in the agenda buffer.

**Comment by gerazov** [comment]
But even if the margin is too large - at least the text in the Agenda will line up nicely with the text in the open buffer. This is :+1: for aesthetics :slightly_smiling_face:

**Comment by gerazov** [comment]
Actually atm with only the signs column turned off in the Agenda with the autocommand @anton-fomin suggested works ok - I can see the tags in their entirety :+1:

**Comment by jgollenz** [comment]
@Nithin745 @anton-fomin @gerazov 

Please have a look at #444 and let me know if it fixes the issue
