### ISSUE TITLE
Make org_meta_return work in insert mode

### ISSUE THREAD

**Issue by mortezadadgar** [nvim-orgmode/orgmode#634]
### Does this feature exist in Emacs orgmode core?

No

### Orgmode link

it's not a emacs specific feature request

### Additional context

the default mapping is not suitable for insert mode but it can be mapped to a appropriate mapping like `<A-CR>` the problem is the mappings are restricted for normal mode

**Comment by seflue** [comment]
I agree, this is a limitation I also struggle with every day (because I use bullet lists and checklists quite a lot).

I already had a look at the code, but the way, how mappings are handled is not as easy to understand as I had hoped. Maybe @kristijanhusak can elaborate on thoughts behind these design decisions and also has some hints how the current structures could be extended to allow user mappings on other modes.

My current intuition is, that maps should alternatively accept a table with a key "mode" and a key "map" and `MapEntry:attach` should handle this case (see snippet).
https://github.com/nvim-orgmode/orgmode/blob/92bfc3fb7ee845d9e58326b0b69f3ed89e84253f/lua/orgmode/config/mappings/map_entry.lua#L64-L103

I think this extension should be handled particularly at the beginning of this iteration over `mapping`:
https://github.com/nvim-orgmode/orgmode/blob/92bfc3fb7ee845d9e58326b0b69f3ed89e84253f/lua/orgmode/config/mappings/map_entry.lua#L94-L102
Something like this:
```lua
local modes
if (type(map) == "table" and map["modes"] and map["map"]) then
  modes = map["modes"]
  map = map["map"]
else
  modes = self.modes
end
-- ...
vim.keymap.set(modes, map, ...)
-- ...
```

Than we would be able to handle a map entry in the config like this:
```lua
org_meta_return = { map = '<M-CR>', modes = { 'n', 'i' }
```

@kristijanhusak What do you think?

**Comment by lyz-code** [comment]
As stated [here](https://github.com/nvim-orgmode/orgmode/issues/472):

> Support for this was added on the latest nightly branch. You can find docs about it here: https://github.com/nvim-orgmode/orgmode/blob/nightly/DOCS.md#use-enter-in-insert-mode-to-add-list-itemscheckboxestodos

**Comment by kristijanhusak** [comment]
Nightly was merged into master so this should now work: https://github.com/nvim-orgmode/orgmode/blob/nightly/DOCS.md#use-enter-in-insert-mode-to-add-list-itemscheckboxestodos
